
import PptxGenJS from "pptxgenjs";

export type PIBriefData = {
  programIncrement: string;
  objectives: Array<{
    id: string;
    description: string;
    businessValue: number;
    status: string;
  }>;
  risks: Array<{
    description: string;
    severity: "high" | "medium" | "low";
    mitigation: string;
  }>;
  confidence: {
    committed: number;
    uncommitted: number;
    overall: number;
  };
  teams: Array<{
    name: string;
    capacity: number;
    velocity: number;
  }>;
};

export type SprintHealthData = {
  sprintName: string;
  startDate: string;
  endDate: string;
  totalStories: number;
  completedStories: number;
  inProgressStories: number;
  blockedStories: number;
  velocity: number;
  burndown: Array<{
    day: string;
    remaining: number;
    ideal: number;
  }>;
  teamMembers: Array<{
    name: string;
    completedPoints: number;
    totalPoints: number;
  }>;
};

export type RiskSummaryData = {
  title: string;
  date: string;
  risks: Array<{
    id: string;
    description: string;
    category: string;
    severity: "critical" | "high" | "medium" | "low";
    probability: number;
    impact: string;
    owner: string;
    mitigation: string;
    status: string;
  }>;
};

export type DependencyHeatmapData = {
  title: string;
  teams: string[];
  dependencies: Array<{
    fromTeam: string;
    toTeam: string;
    count: number;
    description: string;
  }>;
};

export async function generatePIBriefPPT(data: PIBriefData): Promise<Buffer> {
  const pptx = new PptxGenJS();

  // Set presentation properties
  pptx.author = "Atlas Maximus";
  pptx.company = "Agile Excellence";
  pptx.title = `PI ${data.programIncrement} Brief`;

  // Slide 1: Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "1F3864" };
  
  titleSlide.addText(`PI ${data.programIncrement} Brief`, {
    x: 1,
    y: 2,
    w: 8,
    h: 1.5,
    fontSize: 44,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });

  titleSlide.addText("Generated by Atlas Maximus", {
    x: 1,
    y: 4,
    w: 8,
    h: 0.5,
    fontSize: 18,
    color: "E0E0E0",
    align: "center",
  });

  titleSlide.addText(new Date().toLocaleDateString(), {
    x: 1,
    y: 5.5,
    w: 8,
    h: 0.3,
    fontSize: 14,
    color: "B0B0B0",
    align: "center",
  });

  // Slide 2: Objectives Overview
  const objectivesSlide = pptx.addSlide();
  objectivesSlide.addText("PI Objectives", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "1F3864",
  });

  const objectivesRows: any[] = [
    [
      { text: "ID", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Objective", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Business Value", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Status", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
    ],
  ];

  data.objectives.slice(0, 8).forEach((obj) => {
    objectivesRows.push([
      obj.id,
      obj.description,
      obj.businessValue.toString(),
      { 
        text: obj.status,
        opts: {
          fill: obj.status === "Committed" ? "4CAF50" : "FFC107",
          color: "FFFFFF",
        },
      },
    ]);
  });

  objectivesSlide.addTable(objectivesRows, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 4,
    fontSize: 11,
    border: { pt: 1, color: "CCCCCC" },
  });

  // Slide 3: Confidence Vote
  const confidenceSlide = pptx.addSlide();
  confidenceSlide.addText("Team Confidence Vote", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "1F3864",
  });

  const confidenceChartData = [
    {
      name: "Confidence Levels",
      labels: ["Committed", "Uncommitted"],
      values: [data.confidence.committed, data.confidence.uncommitted],
    },
  ];

  objectivesSlide.addChart(pptx.ChartType.pie, confidenceChartData, {
    x: 2,
    y: 2,
    w: 6,
    h: 3.5,
    showTitle: false,
    showLegend: true,
    legendPos: "b",
  });

  confidenceSlide.addText(`Overall Confidence: ${data.confidence.overall}%`, {
    x: 2,
    y: 5.5,
    w: 6,
    h: 0.5,
    fontSize: 24,
    bold: true,
    color: data.confidence.overall >= 80 ? "4CAF50" : data.confidence.overall >= 60 ? "FFC107" : "F44336",
    align: "center",
  });

  // Slide 4: Risks
  const risksSlide = pptx.addSlide();
  risksSlide.addText("Program Risks", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "1F3864",
  });

  const riskRows: any[] = [
    [
      { text: "Risk Description", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Severity", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Mitigation", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
    ],
  ];

  data.risks.forEach((risk) => {
    riskRows.push([
      risk.description,
      {
        text: risk.severity.toUpperCase(),
        opts: {
          fill: risk.severity === "high" ? "F44336" : risk.severity === "medium" ? "FFC107" : "4CAF50",
          color: "FFFFFF",
          bold: true,
        },
      },
      risk.mitigation,
    ]);
  });

  risksSlide.addTable(riskRows, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 4,
    fontSize: 11,
    border: { pt: 1, color: "CCCCCC" },
  });

  // Slide 5: Team Capacity
  const teamsSlide = pptx.addSlide();
  teamsSlide.addText("Team Capacity & Velocity", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "1F3864",
  });

  const teamRows: any[] = [
    [
      { text: "Team", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Capacity (SP)", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
      { text: "Velocity", opts: { bold: true, color: "FFFFFF", fill: "1F3864" } },
    ],
  ];

  data.teams.forEach((team) => {
    teamRows.push([
      team.name,
      team.capacity.toString(),
      team.velocity.toString(),
    ]);
  });

  teamsSlide.addTable(teamRows, {
    x: 2,
    y: 1.5,
    w: 6,
    h: 4,
    fontSize: 12,
    border: { pt: 1, color: "CCCCCC" },
  });

  // Generate and return as buffer
  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return buffer;
}

export async function generateSprintHealthPPT(data: SprintHealthData): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.author = "Atlas Maximus";
  pptx.company = "Agile Excellence";
  pptx.title = `${data.sprintName} Health Report`;

  // Slide 1: Title
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "2E7D32" };
  
  titleSlide.addText(data.sprintName, {
    x: 1,
    y: 2,
    w: 8,
    h: 1,
    fontSize: 44,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });

  titleSlide.addText("Sprint Health Report", {
    x: 1,
    y: 3.2,
    w: 8,
    h: 0.6,
    fontSize: 24,
    color: "E0E0E0",
    align: "center",
  });

  titleSlide.addText(`${data.startDate} - ${data.endDate}`, {
    x: 1,
    y: 4.5,
    w: 8,
    h: 0.4,
    fontSize: 16,
    color: "B0B0B0",
    align: "center",
  });

  // Slide 2: Sprint Metrics
  const metricsSlide = pptx.addSlide();
  metricsSlide.addText("Sprint Metrics", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "2E7D32",
  });

  // Key metrics boxes
  const metrics = [
    { label: "Total Stories", value: data.totalStories, color: "1976D2" },
    { label: "Completed", value: data.completedStories, color: "4CAF50" },
    { label: "In Progress", value: data.inProgressStories, color: "FFC107" },
    { label: "Blocked", value: data.blockedStories, color: "F44336" },
  ];

  metrics.forEach((metric, index) => {
    const x = 1 + (index * 2.2);
    metricsSlide.addShape(pptx.ShapeType.rect, {
      x,
      y: 2,
      w: 2,
      h: 1.5,
      fill: { color: metric.color },
    });
    
    metricsSlide.addText(metric.value.toString(), {
      x,
      y: 2.2,
      w: 2,
      h: 0.6,
      fontSize: 36,
      bold: true,
      color: "FFFFFF",
      align: "center",
    });
    
    metricsSlide.addText(metric.label, {
      x,
      y: 2.9,
      w: 2,
      h: 0.4,
      fontSize: 14,
      color: "FFFFFF",
      align: "center",
    });
  });

  // Velocity
  metricsSlide.addText(`Sprint Velocity: ${data.velocity} SP`, {
    x: 2.5,
    y: 4.5,
    w: 5,
    h: 0.6,
    fontSize: 24,
    bold: true,
    color: "1F3864",
    align: "center",
  });

  // Slide 3: Team Performance
  if (data.teamMembers.length > 0) {
    const teamSlide = pptx.addSlide();
    teamSlide.addText("Team Performance", {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.75,
      fontSize: 32,
      bold: true,
      color: "2E7D32",
    });

    const teamRows: any[] = [
      [
        { text: "Team Member", opts: { bold: true, color: "FFFFFF", fill: "2E7D32" } },
        { text: "Completed Points", opts: { bold: true, color: "FFFFFF", fill: "2E7D32" } },
        { text: "Total Points", opts: { bold: true, color: "FFFFFF", fill: "2E7D32" } },
        { text: "Completion %", opts: { bold: true, color: "FFFFFF", fill: "2E7D32" } },
      ],
    ];

    data.teamMembers.forEach((member) => {
      const completion = member.totalPoints > 0 
        ? Math.round((member.completedPoints / member.totalPoints) * 100)
        : 0;
      
      teamRows.push([
        member.name,
        member.completedPoints.toString(),
        member.totalPoints.toString(),
        {
          text: `${completion}%`,
          opts: {
            fill: completion >= 80 ? "4CAF50" : completion >= 60 ? "FFC107" : "F44336",
            color: "FFFFFF",
          },
        },
      ]);
    });

    teamSlide.addTable(teamRows, {
      x: 1,
      y: 1.5,
      w: 8,
      h: 4,
      fontSize: 12,
      border: { pt: 1, color: "CCCCCC" },
    });
  }

  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return buffer;
}

export async function generateRiskSummaryPPT(data: RiskSummaryData): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.author = "Atlas Maximus";
  pptx.company = "Agile Excellence";
  pptx.title = data.title;

  // Slide 1: Title
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "C62828" };
  
  titleSlide.addText(data.title, {
    x: 1,
    y: 2.5,
    w: 8,
    h: 1,
    fontSize: 44,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });

  titleSlide.addText(data.date, {
    x: 1,
    y: 4,
    w: 8,
    h: 0.4,
    fontSize: 16,
    color: "E0E0E0",
    align: "center",
  });

  // Slide 2: Risk Overview
  const overviewSlide = pptx.addSlide();
  overviewSlide.addText("Risk Overview", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "C62828",
  });

  const severityCounts = {
    critical: data.risks.filter((r) => r.severity === "critical").length,
    high: data.risks.filter((r) => r.severity === "high").length,
    medium: data.risks.filter((r) => r.severity === "medium").length,
    low: data.risks.filter((r) => r.severity === "low").length,
  };

  const riskCountBoxes = [
    { label: "Critical", count: severityCounts.critical, color: "B71C1C" },
    { label: "High", count: severityCounts.high, color: "F44336" },
    { label: "Medium", count: severityCounts.medium, color: "FFC107" },
    { label: "Low", count: severityCounts.low, color: "4CAF50" },
  ];

  riskCountBoxes.forEach((box, index) => {
    const x = 1.5 + (index * 1.8);
    overviewSlide.addShape(pptx.ShapeType.rect, {
      x,
      y: 2,
      w: 1.5,
      h: 1.5,
      fill: { color: box.color },
    });
    
    overviewSlide.addText(box.count.toString(), {
      x,
      y: 2.2,
      w: 1.5,
      h: 0.6,
      fontSize: 36,
      bold: true,
      color: "FFFFFF",
      align: "center",
    });
    
    overviewSlide.addText(box.label, {
      x,
      y: 2.9,
      w: 1.5,
      h: 0.4,
      fontSize: 14,
      color: "FFFFFF",
      align: "center",
    });
  });

  overviewSlide.addText(`Total Risks: ${data.risks.length}`, {
    x: 2.5,
    y: 4.5,
    w: 5,
    h: 0.6,
    fontSize: 24,
    bold: true,
    color: "1F3864",
    align: "center",
  });

  // Slide 3: Detailed Risks
  const detailSlide = pptx.addSlide();
  detailSlide.addText("Risk Details", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "C62828",
  });

  const riskRows: any[] = [
    [
      { text: "ID", opts: { bold: true, color: "FFFFFF", fill: "C62828", fontSize: 10 } },
      { text: "Description", opts: { bold: true, color: "FFFFFF", fill: "C62828", fontSize: 10 } },
      { text: "Severity", opts: { bold: true, color: "FFFFFF", fill: "C62828", fontSize: 10 } },
      { text: "Owner", opts: { bold: true, color: "FFFFFF", fill: "C62828", fontSize: 10 } },
      { text: "Status", opts: { bold: true, color: "FFFFFF", fill: "C62828", fontSize: 10 } },
    ],
  ];

  data.risks.slice(0, 10).forEach((risk) => {
    const severityColor =
      risk.severity === "critical"
        ? "B71C1C"
        : risk.severity === "high"
        ? "F44336"
        : risk.severity === "medium"
        ? "FFC107"
        : "4CAF50";

    riskRows.push([
      risk.id,
      risk.description.substring(0, 60) + (risk.description.length > 60 ? "..." : ""),
      {
        text: risk.severity.toUpperCase(),
        opts: { fill: severityColor, color: "FFFFFF", bold: true },
      },
      risk.owner,
      risk.status,
    ]);
  });

  detailSlide.addTable(riskRows, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 4,
    fontSize: 9,
    border: { pt: 1, color: "CCCCCC" },
  });

  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return buffer;
}

export async function generateDependencyHeatmapPPT(data: DependencyHeatmapData): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.author = "Atlas Maximus";
  pptx.company = "Agile Excellence";
  pptx.title = data.title;

  // Slide 1: Title
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "6A1B9A" };
  
  titleSlide.addText(data.title, {
    x: 1,
    y: 2.5,
    w: 8,
    h: 1,
    fontSize: 44,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });

  titleSlide.addText("Team Dependency Analysis", {
    x: 1,
    y: 3.8,
    w: 8,
    h: 0.5,
    fontSize: 20,
    color: "E0E0E0",
    align: "center",
  });

  // Slide 2: Dependency Matrix
  const matrixSlide = pptx.addSlide();
  matrixSlide.addText("Dependency Heatmap", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "6A1B9A",
  });

  // Create dependency matrix
  const matrixRows: any[] = [
    [
      { text: "From \\ To", opts: { bold: true, fill: "6A1B9A", color: "FFFFFF" } },
      ...data.teams.map((team) => ({
        text: team,
        opts: { bold: true, fill: "6A1B9A", color: "FFFFFF", fontSize: 10 },
      })),
    ],
  ];

  data.teams.forEach((fromTeam) => {
    const row: any[] = [{ text: fromTeam, opts: { bold: true, fill: "E1BEE7" } }];
    
    data.teams.forEach((toTeam) => {
      if (fromTeam === toTeam) {
        row.push({ text: "-", opts: { fill: "F5F5F5" } });
      } else {
        const dep = data.dependencies.find(
          (d) => d.fromTeam === fromTeam && d.toTeam === toTeam
        );
        const count = dep?.count || 0;
        const color =
          count === 0
            ? "E8F5E9"
            : count <= 2
            ? "FFF9C4"
            : count <= 5
            ? "FFCC80"
            : "EF5350";
        
        row.push({
          text: count.toString(),
          opts: { fill: color, bold: count > 5, fontSize: 11 },
        });
      }
    });
    
    matrixRows.push(row);
  });

  matrixSlide.addTable(matrixRows, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 4,
    fontSize: 11,
    border: { pt: 1, color: "CCCCCC" },
  });

  // Slide 3: Key Dependencies
  const detailsSlide = pptx.addSlide();
  detailsSlide.addText("Key Dependencies", {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.75,
    fontSize: 32,
    bold: true,
    color: "6A1B9A",
  });

  const topDeps = data.dependencies
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  const depRows: any[] = [
    [
      { text: "From Team", opts: { bold: true, color: "FFFFFF", fill: "6A1B9A" } },
      { text: "To Team", opts: { bold: true, color: "FFFFFF", fill: "6A1B9A" } },
      { text: "Count", opts: { bold: true, color: "FFFFFF", fill: "6A1B9A" } },
      { text: "Description", opts: { bold: true, color: "FFFFFF", fill: "6A1B9A" } },
    ],
  ];

  topDeps.forEach((dep) => {
    depRows.push([
      dep.fromTeam,
      dep.toTeam,
      {
        text: dep.count.toString(),
        opts: {
          bold: true,
          fill: dep.count > 5 ? "EF5350" : dep.count > 2 ? "FFCC80" : "FFF9C4",
        },
      },
      dep.description.substring(0, 50) + (dep.description.length > 50 ? "..." : ""),
    ]);
  });

  detailsSlide.addTable(depRows, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 4,
    fontSize: 11,
    border: { pt: 1, color: "CCCCCC" },
  });

  const buffer = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  return buffer;
}
