
import { Document, Paragraph, Table, TableCell, TableRow, TextRun, AlignmentType, BorderStyle, WidthType, Packer } from "docx";
import {
  PIBriefData,
  SprintHealthData,
  RiskSummaryData,
  DependencyHeatmapData,
} from "./ppt-generator";

export async function generatePIBriefDoc(data: PIBriefData): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            text: `PI ${data.programIncrement} Brief`,
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            text: `Generated by Atlas Maximus - ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          // Objectives Section
          new Paragraph({
            text: "PI Objectives",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "ID", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Objective", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Business Value", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Status", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                ],
              }),
              ...data.objectives.map(
                (obj) =>
                  new TableRow({
                    children: [
                      new TableCell({ children: [new Paragraph(obj.id)] }),
                      new TableCell({ children: [new Paragraph(obj.description)] }),
                      new TableCell({ children: [new Paragraph(obj.businessValue.toString())] }),
                      new TableCell({
                        children: [new Paragraph(obj.status)],
                        shading: { fill: obj.status === "Committed" ? "4CAF50" : "FFC107" },
                      }),
                    ],
                  })
              ),
            ],
          }),

          // Confidence Vote Section
          new Paragraph({
            text: "Team Confidence Vote",
            heading: "Heading2",
            spacing: { before: 600, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Committed: ${data.confidence.committed}%`,
                bold: true,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Uncommitted: ${data.confidence.uncommitted}%`,
                bold: true,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Overall Confidence: ${data.confidence.overall}%`,
                bold: true,
                size: 32,
                color: data.confidence.overall >= 80 ? "4CAF50" : data.confidence.overall >= 60 ? "FFC107" : "F44336",
              }),
            ],
            spacing: { after: 200 },
          }),

          // Risks Section
          new Paragraph({
            text: "Program Risks",
            heading: "Heading2",
            spacing: { before: 600, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Description", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Severity", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Mitigation", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                ],
              }),
              ...data.risks.map(
                (risk) =>
                  new TableRow({
                    children: [
                      new TableCell({ children: [new Paragraph(risk.description)] }),
                      new TableCell({
                        children: [new Paragraph(risk.severity.toUpperCase())],
                        shading: {
                          fill:
                            risk.severity === "high"
                              ? "F44336"
                              : risk.severity === "medium"
                              ? "FFC107"
                              : "4CAF50",
                        },
                      }),
                      new TableCell({ children: [new Paragraph(risk.mitigation)] }),
                    ],
                  })
              ),
            ],
          }),

          // Team Capacity Section
          new Paragraph({
            text: "Team Capacity & Velocity",
            heading: "Heading2",
            spacing: { before: 600, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Team", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Capacity (SP)", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Velocity", bold: true })] })],
                    shading: { fill: "1F3864" },
                  }),
                ],
              }),
              ...data.teams.map(
                (team) =>
                  new TableRow({
                    children: [
                      new TableCell({ children: [new Paragraph(team.name)] }),
                      new TableCell({ children: [new Paragraph(team.capacity.toString())] }),
                      new TableCell({ children: [new Paragraph(team.velocity.toString())] }),
                    ],
                  })
              ),
            ],
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

export async function generateSprintHealthDoc(data: SprintHealthData): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            text: data.sprintName,
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),
          new Paragraph({
            text: "Sprint Health Report",
            heading: "Heading2",
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
          }),
          new Paragraph({
            text: `${data.startDate} - ${data.endDate}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          // Sprint Metrics
          new Paragraph({
            text: "Sprint Metrics",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Total Stories: ${data.totalStories}`, bold: true })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Completed: ${data.completedStories}`, bold: true })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `In Progress: ${data.inProgressStories}`, bold: true })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [new TextRun({ text: `Blocked: ${data.blockedStories}`, bold: true })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Sprint Velocity: ${data.velocity} SP`,
                bold: true,
                size: 28,
              }),
            ],
            spacing: { after: 400 },
          }),

          // Team Performance
          ...(data.teamMembers.length > 0
            ? [
                new Paragraph({
                  text: "Team Performance",
                  heading: "Heading2",
                  spacing: { before: 400, after: 200 },
                }),
                new Table({
                  width: { size: 100, type: WidthType.PERCENTAGE },
                  rows: [
                    new TableRow({
                      children: [
                        new TableCell({
                          children: [new Paragraph({ children: [new TextRun({ text: "Team Member", bold: true })] })],
                          shading: { fill: "2E7D32" },
                        }),
                        new TableCell({
                          children: [new Paragraph({ children: [new TextRun({ text: "Completed Points", bold: true })] })],
                          shading: { fill: "2E7D32" },
                        }),
                        new TableCell({
                          children: [new Paragraph({ children: [new TextRun({ text: "Total Points", bold: true })] })],
                          shading: { fill: "2E7D32" },
                        }),
                        new TableCell({
                          children: [new Paragraph({ children: [new TextRun({ text: "Completion %", bold: true })] })],
                          shading: { fill: "2E7D32" },
                        }),
                      ],
                    }),
                    ...data.teamMembers.map((member) => {
                      const completion =
                        member.totalPoints > 0
                          ? Math.round((member.completedPoints / member.totalPoints) * 100)
                          : 0;

                      return new TableRow({
                        children: [
                          new TableCell({ children: [new Paragraph(member.name)] }),
                          new TableCell({ children: [new Paragraph(member.completedPoints.toString())] }),
                          new TableCell({ children: [new Paragraph(member.totalPoints.toString())] }),
                          new TableCell({
                            children: [new Paragraph(`${completion}%`)],
                            shading: {
                              fill: completion >= 80 ? "4CAF50" : completion >= 60 ? "FFC107" : "F44336",
                            },
                          }),
                        ],
                      });
                    }),
                  ],
                }),
              ]
            : []),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

export async function generateRiskSummaryDoc(data: RiskSummaryData): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: data.title,
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),
          new Paragraph({
            text: data.date,
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          new Paragraph({
            text: "Risk Overview",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Total Risks: ${data.risks.length}`,
                bold: true,
                size: 24,
              }),
            ],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Critical: ${data.risks.filter((r) => r.severity === "critical").length}`,
                bold: true,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `High: ${data.risks.filter((r) => r.severity === "high").length}`,
                bold: true,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Medium: ${data.risks.filter((r) => r.severity === "medium").length}`,
                bold: true,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Low: ${data.risks.filter((r) => r.severity === "low").length}`,
                bold: true,
              }),
            ],
            spacing: { after: 400 },
          }),

          new Paragraph({
            text: "Risk Details",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "ID", bold: true })] })],
                    shading: { fill: "C62828" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Description", bold: true })] })],
                    shading: { fill: "C62828" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Severity", bold: true })] })],
                    shading: { fill: "C62828" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Owner", bold: true })] })],
                    shading: { fill: "C62828" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Status", bold: true })] })],
                    shading: { fill: "C62828" },
                  }),
                ],
              }),
              ...data.risks.map(
                (risk) =>
                  new TableRow({
                    children: [
                      new TableCell({ children: [new Paragraph(risk.id)] }),
                      new TableCell({ children: [new Paragraph(risk.description)] }),
                      new TableCell({
                        children: [new Paragraph(risk.severity.toUpperCase())],
                        shading: {
                          fill:
                            risk.severity === "critical"
                              ? "B71C1C"
                              : risk.severity === "high"
                              ? "F44336"
                              : risk.severity === "medium"
                              ? "FFC107"
                              : "4CAF50",
                        },
                      }),
                      new TableCell({ children: [new Paragraph(risk.owner)] }),
                      new TableCell({ children: [new Paragraph(risk.status)] }),
                    ],
                  })
              ),
            ],
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}

export async function generateDependencyHeatmapDoc(data: DependencyHeatmapData): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: data.title,
            heading: "Heading1",
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),
          new Paragraph({
            text: "Team Dependency Analysis",
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          new Paragraph({
            text: "Key Dependencies",
            heading: "Heading2",
            spacing: { before: 400, after: 200 },
          }),

          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "From Team", bold: true })] })],
                    shading: { fill: "6A1B9A" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "To Team", bold: true })] })],
                    shading: { fill: "6A1B9A" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Count", bold: true })] })],
                    shading: { fill: "6A1B9A" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Description", bold: true })] })],
                    shading: { fill: "6A1B9A" },
                  }),
                ],
              }),
              ...data.dependencies
                .sort((a, b) => b.count - a.count)
                .map(
                  (dep) =>
                    new TableRow({
                      children: [
                        new TableCell({ children: [new Paragraph(dep.fromTeam)] }),
                        new TableCell({ children: [new Paragraph(dep.toTeam)] }),
                        new TableCell({
                          children: [new Paragraph(dep.count.toString())],
                          shading: {
                            fill: dep.count > 5 ? "EF5350" : dep.count > 2 ? "FFCC80" : "FFF9C4",
                          },
                        }),
                        new TableCell({ children: [new Paragraph(dep.description)] }),
                      ],
                    })
                ),
            ],
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}
